### ISSUE TITLE
Footway crossings shared with bicycles may be tagged highway=path

### ISSUE THREAD

**Issue by naomap** [nlehuby/sidewalker#3]
According to the wiki page https://wiki.openstreetmap.org/wiki/Tag:footway%3Dcrossing, footway crossings shared with bicycles may be tagged highway=path + path=crossing. These are currently not rendered on OSM Sidewalker.

Example in Créteil : https://www.openstreetmap.org/way/1157012460

**Comment by nlehuby** [comment]
Thanks for the feedback.

From my point of view, it's not very consistent with [the doc for highway=path](https://wiki.openstreetmap.org/wiki/FR:Tag:highway%3Dpath) :thinking:

> Cet attribut [highway=path] est utilisé pour les voies où highway=footway, highway=cycleway (...) ne seraient pas appropriés ou inadéquats (...).
> En milieu urbain, il est préférable d’utiliser highway=footway (avec bicycle=yes si nécessaire) sur les aménagements principalement destinés à un usage piéton. 

But anyway, I have added path=crossing as a "Passage piéton"
