### ISSUE TITLE
sidewalk:both

### ISSUE THREAD

**Issue by gosgtan** [nlehuby/sidewalker#5]
Bonjour,

J'ai cartographié les trottoirs sur 3 villes par chez moi, avec sidewalk:both quand les trottoirs sont présents des deux côtés, sinon sidewalk:left, sidewalk:right, ou sidewalk:separate quand c'est à part. Mais sur votre outil, sidewalk:both ne semble pas être pris en compte : "Rue sans indication de trottoir". Est-ce que c'est moi qui ai mal utilisé les tags ou ce n'est pas pris en compte? 

Merci !

**Comment by nlehuby** [comment]
Bonjour,

en effet `sidewalk:both` n'est pas pris en compte. Si l'objectif est d'indiquer qu'il y a un trottoir des 2 côtés, j'utiliserais plutôt `sidewalk`=`both`.

**Comment by gosgtan** [comment]
Bonjour,

Merci pour votre réponse. C'est pourtant un tag d'usage..

**Comment by nlehuby** [comment]
J'ai ajouté le support de `sidewalk:both`=`yes` mais je maintiens que ce tag ne devrait pas exister vu que `sidewalk`=`both` a le même sens.
